import type { MetadataRoute } from 'next';
import { env } from '@/lib/env';

// Root /sitemap.xml — short list of static pages only. The huge programmatic
// sitemaps live at /routes/sitemap/[id].xml and /airports/sitemap/[id].xml
// (generated by Next.js 16 generateSitemaps() in those segments).
//
// For mega-scale, submit /sitemap-index.xml to Search Console — that's a
// proper <sitemapindex> referencing every chunk.

export const revalidate = 3600;

export default function sitemap(): MetadataRoute.Sitemap {
  const base = env.siteUrl;
  return [
    { url: `${base}/`,       changeFrequency: 'weekly',  priority: 1.0 },
    { url: `${base}/hotels`, changeFrequency: 'monthly', priority: 0.3 },
    { url: `${base}/cars`,   changeFrequency: 'monthly', priority: 0.3 },
  ];
}
